import {
  getPlaylistsForWriter,
  getPlaylistItemsForWriter,
  createPlaylist,
  addVideoToPlaylist,
} from "./youtube";
import { createPlaylistKey } from "../utils/createPlaylistCandidate";

const YTWL_PREFIX = "YTWL:v1:";

function createYTWLId(playlist) {
 
  const ytwlId = `${YTWL_PREFIX}${createPlaylistKey(playlist.meta.values)}`;

  console.log("[YTWL] Generated ytwlId:", ytwlId);

  return ytwlId;
}

function createPlaylistDescription(ytwlId) {
  const description = ["Generated by YT Watch Later", "", ytwlId].join("\n");

  return description;
}

async function findGeneratedPlaylist(accessToken, ytwlId) {
  console.log("[YTWL] Searching for existing playlist:", ytwlId);

  let pageToken = "";
  let page = 1;

  while (true) {
    console.log(`[YTWL] Fetching playlists page ${page}...`);

    const response = await getPlaylistsForWriter(accessToken, pageToken);

    console.log(`[YTWL] Playlists page ${page} response:`, response);

    const playlists = response.playlists || [];

    console.log(`[YTWL] Found ${playlists.length} playlists on page ${page}`);

    const found = playlists.find((playlist) =>
      playlist.description?.includes(ytwlId)
    );

    if (found) {
      console.log("[YTWL] Existing generated playlist found:", found);
      return found;
    }

    if (!response.nextPageToken) {
      console.log("[YTWL] No more playlist pages. Playlist not found.");
      return null;
    }

    pageToken = response.nextPageToken;
    page++;
  }
}

async function getExistingVideoIds(accessToken, playlistId) {
  console.log("[YTWL] Fetching existing videos from playlist:", playlistId);

  const videoIds = new Set();

  let pageToken = "";
  let page = 1;

  while (true) {
    console.log(
      `[YTWL] Fetching playlist items page ${page} for playlist ${playlistId}...`
    );

    const response = await getPlaylistItemsForWriter(
      accessToken,
      playlistId,
      pageToken
    );

    console.log(`[YTWL] Playlist items page ${page} response:`, response);

    const items = response.items || [];

    console.log(`[YTWL] Found ${items.length} video IDs on page ${page}`);

    for (const videoId of items) {
      videoIds.add(videoId);
    }

    if (!response.nextPageToken) {
      break;
    }

    pageToken = response.nextPageToken;
    page++;
  }

  console.log(`[YTWL] Total existing videos in playlist: ${videoIds.size}`);

  return videoIds;
}

async function waitForNewPlaylist(
  accessToken,
  playlistId
) {
  const maxAttempts = 5;

  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    console.log(
      `[YTWL] Checking playlist propagation: attempt ${attempt}/${maxAttempts}`
    );

    try {
      const response =
        await getPlaylistItemsForWriter(
          accessToken,
          playlistId
        );

      console.log(
        "[YTWL] Playlist is now available through playlistItems.list."
      );

      return new Set(response.items || []);
    } catch (error) {
      const isPropagationError =
        error?.status === 404 &&
        error?.reason === "playlistNotFound";

      if (
        !isPropagationError ||
        attempt === maxAttempts
      ) {
        throw error;
      }

      const delay =
        1000 * 2 ** (attempt - 1);

      console.log(
        `[YTWL] Playlist not propagated yet. ` +
          `Waiting ${delay}ms before retry...`
      );

      await new Promise((resolve) =>
        setTimeout(resolve, delay)
      );
    }
  }

  throw new Error(
    "New YouTube playlist did not become available"
  );
}

export async function syncGeneratedPlaylist(
  accessToken,
  generatedPlaylist
) {

    console.log(
    "[YTWL] generatedPlaylist:",
    generatedPlaylist
  );

  if (!accessToken) {
    console.error(
      "[YTWL] ERROR: accessToken is missing!"
    );

    throw new Error(
      "YouTube access token is missing"
    );
  }

  if (!generatedPlaylist) {
    console.error(
      "[YTWL] ERROR: generatedPlaylist is missing!"
    );

    throw new Error(
      "generatedPlaylist is missing"
    );
  }

  const ytwlId =
    createYTWLId(generatedPlaylist);

  console.log(
    "[YTWL] Looking for existing generated playlist...",ytwlId
  );

  // find if playlist with ytwlId already exists in user's yt account
  let youtubePlaylist =
    await findGeneratedPlaylist(
      accessToken,
      ytwlId
    );

  let created = false;
  let existingVideoIds;

  // No existing playlist then create playlist
  if (!youtubePlaylist) {

    console.log(
      "[YTWL] Creating new YouTube playlist..."
    );

    const description =
      createPlaylistDescription(ytwlId)

    youtubePlaylist = await createPlaylist(
      accessToken,
      generatedPlaylist.name,
      description,
      "private"
    );

    console.log(
      "[YTWL] YouTube playlist created successfully:",
      youtubePlaylist
    );

    created = true;
  } else {
    console.log(
      "[YTWL] Using existing YouTube playlist:",
      youtubePlaylist
    );
  }

  const playlistId = youtubePlaylist.id;


  if (!playlistId) {
    console.error(
      "[YTWL] ERROR: YouTube playlist was returned without an ID!",
      youtubePlaylist
    );

    throw new Error(
      "YouTube playlist ID is missing"
    );
  }

  // Get existing videos
  if (created) {

    existingVideoIds =
      await waitForNewPlaylist(
        accessToken,
        playlistId
      );

    console.log(
      "[YTWL] New playlist is propagated."
    );
  } else {
    console.log(
      "[YTWL] Fetching existing video IDs..."
    );

    existingVideoIds =
      await getExistingVideoIds(
        accessToken,
        playlistId
      );
  }


  const desiredVideoIds = new Set(
    generatedPlaylist.videoIds || []
  );

  console.log(
    "[YTWL] Desired video IDs:",
    Array.from(desiredVideoIds)
  );


  const alreadyPresent = [];
  const videosToInsert = [];

  for (const videoId of desiredVideoIds) {
    if (existingVideoIds.has(videoId)) {

      alreadyPresent.push(videoId);
    } else {

      videosToInsert.push(videoId);
    }
  }

  // Insert missing videos
  const added = [];
  const failed = [];

  for (const videoId of videosToInsert) {
    console.log(
      `[YTWL] Attempting to add video: ${videoId}`
    );

    try {
      await addVideoToPlaylist(
        accessToken,
        playlistId,
        videoId
      );

      console.log(
        `[YTWL] Successfully added video: ${videoId}`
      );

      added.push(videoId);
    } catch (error) {
      console.error(
        `[YTWL] FAILED to add video: ${videoId}`,
        error
      );

      failed.push({
        videoId,
        error:
          error?.message ||
          String(error),
      });
    }
  }


  let status = "completed";

  if (failed.length > 0) {
    if (added.length > 0) {
      status = "partial";
    } else {
      status = "failed";
    }
  }

  const result = {
    name: generatedPlaylist.name,
    ytwlId,
    youtubePlaylistId: playlistId,
    created,
    status,
    totalVideos: desiredVideoIds.size,
    alreadyPresent,
    added,
    failed,
  };

  console.log("[YTWL] Result:", result);
  return result;
}
