import {
  getPlaylistsForWriter,
  getPlaylistItemsForWriter,
  createPlaylist,
  addVideoToPlaylist,
} from "./youtube";
import { createPlaylistKey } from "../utils/createPlaylistKey";

const YTWL_PREFIX = "YTWL:v1:";

function createYTWLId(playlist) {
  return `${YTWL_PREFIX}${createPlaylistKey(playlist.meta.values)}`;
}

function createPlaylistDescription(ytwlId) {
  return ["Generated by YT Watch Later", "", ytwlId].join("\n");
}

async function findGeneratedPlaylist(accessToken, ytwlId) {
  let pageToken = "";

  while (true) {
    const response = await getPlaylistsForWriter(accessToken, pageToken);

    const found = response.playlists.find((playlist) =>
      playlist.description?.includes(ytwlId)
    );

    if (found) {
      return found;
    }

    if (!response.nextPageToken) {
      return null;
    }

    pageToken = response.nextPageToken;
  }
}

async function getExistingVideoIds(accessToken, playlistId) {
  const videoIds = new Set();

  let pageToken = "";

  while (true) {
    const response = await getPlaylistItemsForWriter(
      accessToken,
      playlistId,
      pageToken
    );

    for (const videoId of response.items) {
      videoIds.add(videoId);
    }

    if (!response.nextPageToken) {
      break;
    }

    pageToken = response.nextPageToken;
  }

  return videoIds;
}

export async function syncGeneratedPlaylist(accessToken, generatedPlaylist) {
  const ytwlId = createYTWLId(generatedPlaylist);

  let youtubePlaylist = await findGeneratedPlaylist(accessToken, ytwlId);

  let created = false;

  if (!youtubePlaylist) {
    const description = createPlaylistDescription(ytwlId);

    youtubePlaylist = await createPlaylist(
      accessToken,
      generatedPlaylist.name,
      description,
      "private"
    );

    created = true;
  }

  const playlistId = youtubePlaylist.id;

  const existingVideoIds = await getExistingVideoIds(accessToken, playlistId);

  const desiredVideoIds = new Set(generatedPlaylist.videoIds || []);

  const alreadyPresent = [];
  const videosToInsert = [];

  for (const videoId of desiredVideoIds) {
    if (existingVideoIds.has(videoId)) {
      alreadyPresent.push(videoId);
    } else {
      videosToInsert.push(videoId);
    }
  }

  const added = [];
  const failed = [];

  for (const videoId of videosToInsert) {
    try {
      await addVideoToPlaylist(accessToken, playlistId, videoId);

      added.push(videoId);
    } catch (error) {
      failed.push({
        videoId,
        error: error.message,
      });
    }
  }

  let status = "completed";

  if (failed.length > 0) {
    if (added.length > 0) {
      status = "partial";
    } else {
      status = "failed";
    }
  }

  return {
    name: generatedPlaylist.name,
    ytwlId,
    youtubePlaylistId: playlistId,
    created,
    status,
    totalVideos: desiredVideoIds.size,
    alreadyPresent,
    added,
    failed,
  };
}
