import {
  getPlaylistsForWriter,
  getPlaylistItemsForWriter,
  createPlaylist,
  addVideoToPlaylist,
} from "./youtube";
import { createPlaylistKey } from "../utils/createPlaylistCandidate";

const YTWL_PREFIX = "YTWL:v1:";

function createYTWLId(playlist) {
 
  const ytwlId = `${YTWL_PREFIX}${createPlaylistKey(playlist.meta.values)}`;

  console.log("[YTWL] Generated ytwlId:", ytwlId);

  return ytwlId;
}

function createPlaylistDescription(ytwlId) {
  const description = ["Generated by YT Watch Later", "", ytwlId].join("\n");

  console.log("[YTWL] Generated playlist description:", description);

  return description;
}

async function findGeneratedPlaylist(accessToken, ytwlId) {
  console.log("[YTWL] Searching for existing playlist:", ytwlId);

  let pageToken = "";
  let page = 1;

  while (true) {
    console.log(`[YTWL] Fetching playlists page ${page}...`);

    const response = await getPlaylistsForWriter(accessToken, pageToken);

    console.log(`[YTWL] Playlists page ${page} response:`, response);

    const playlists = response.playlists || [];

    console.log(`[YTWL] Found ${playlists.length} playlists on page ${page}`);

    const found = playlists.find((playlist) =>
      playlist.description?.includes(ytwlId)
    );

    if (found) {
      console.log("[YTWL] Existing generated playlist found:", found);
      return found;
    }

    if (!response.nextPageToken) {
      console.log("[YTWL] No more playlist pages. Playlist not found.");
      return null;
    }

    pageToken = response.nextPageToken;
    page++;
  }
}

async function getExistingVideoIds(accessToken, playlistId) {
  console.log("[YTWL] Fetching existing videos from playlist:", playlistId);

  const videoIds = new Set();

  let pageToken = "";
  let page = 1;

  while (true) {
    console.log(
      `[YTWL] Fetching playlist items page ${page} for playlist ${playlistId}...`
    );

    const response = await getPlaylistItemsForWriter(
      accessToken,
      playlistId,
      pageToken
    );

    console.log(`[YTWL] Playlist items page ${page} response:`, response);

    const items = response.items || [];

    console.log(`[YTWL] Found ${items.length} video IDs on page ${page}`);

    for (const videoId of items) {
      videoIds.add(videoId);
    }

    if (!response.nextPageToken) {
      break;
    }

    pageToken = response.nextPageToken;
    page++;
  }

  console.log(`[YTWL] Total existing videos in playlist: ${videoIds.size}`);

  return videoIds;
}

export async function syncGeneratedPlaylist(accessToken, generatedPlaylist) {
  console.log("========================================");
  console.log("[YTWL] START syncGeneratedPlaylist");
  console.log("========================================");

  console.log("[YTWL] generatedPlaylist:", generatedPlaylist);

  if (!accessToken) {
    console.error("[YTWL] ERROR: accessToken is missing!");
    throw new Error("YouTube access token is missing");
  }

  if (!generatedPlaylist) {
    console.error("[YTWL] ERROR: generatedPlaylist is missing!");
    throw new Error("generatedPlaylist is missing");
  }

  const ytwlId = createYTWLId(generatedPlaylist);

  console.log("[YTWL] ytwlId:", ytwlId);

  console.log("[YTWL] Looking for existing generated playlist...");

  let youtubePlaylist = await findGeneratedPlaylist(accessToken, ytwlId);

  let created = false;

  if (!youtubePlaylist) {
    console.log("[YTWL] Generated playlist does not exist.");
    console.log("[YTWL] Creating new YouTube playlist...");

    const description = createPlaylistDescription(ytwlId);

    console.log("[YTWL] Playlist name:", generatedPlaylist.name);
    console.log("[YTWL] Playlist description:", description);

    youtubePlaylist = await createPlaylist(
      accessToken,
      generatedPlaylist.name,
      description,
      "private"
    );

    console.log(
      "[YTWL] YouTube playlist created successfully:",
      youtubePlaylist
    );

    created = true;
  } else {
    console.log("[YTWL] Using existing YouTube playlist:", youtubePlaylist);
  }

  const playlistId = youtubePlaylist.id;

  console.log("[YTWL] YouTube playlist ID:", playlistId);

  if (!playlistId) {
    console.error(
      "[YTWL] ERROR: YouTube playlist was returned without an ID!",
      youtubePlaylist
    );

    throw new Error("YouTube playlist ID is missing");
  }

  console.log("[YTWL] Fetching existing video IDs...");

  const existingVideoIds = await getExistingVideoIds(accessToken, playlistId);

  console.log("[YTWL] Existing video IDs:", Array.from(existingVideoIds));

  const desiredVideoIds = new Set(generatedPlaylist.videoIds || []);

  console.log("[YTWL] Desired video IDs:", Array.from(desiredVideoIds));

  console.log(`[YTWL] Desired videos: ${desiredVideoIds.size}`);

  console.log(`[YTWL] Existing videos: ${existingVideoIds.size}`);

  const alreadyPresent = [];
  const videosToInsert = [];

  for (const videoId of desiredVideoIds) {
    if (existingVideoIds.has(videoId)) {
      console.log(`[YTWL] Video already exists in playlist: ${videoId}`);

      alreadyPresent.push(videoId);
    } else {
      console.log(`[YTWL] Video needs to be added: ${videoId}`);

      videosToInsert.push(videoId);
    }
  }

  console.log(`[YTWL] Videos already present: ${alreadyPresent.length}`);

  console.log(`[YTWL] Videos to insert: ${videosToInsert.length}`);

  const added = [];
  const failed = [];

  for (const videoId of videosToInsert) {
    console.log(`[YTWL] Attempting to add video: ${videoId}`);

    try {
      await addVideoToPlaylist(accessToken, playlistId, videoId);

      console.log(`[YTWL] Successfully added video: ${videoId}`);

      added.push(videoId);
    } catch (error) {
      console.error(`[YTWL] FAILED to add video: ${videoId}`, error);

      failed.push({
        videoId,
        error: error?.message || String(error),
      });
    }
  }

  let status = "completed";

  if (failed.length > 0) {
    if (added.length > 0) {
      status = "partial";
    } else {
      status = "failed";
    }
  }

  const result = {
    name: generatedPlaylist.name,
    ytwlId,
    youtubePlaylistId: playlistId,
    created,
    status,
    totalVideos: desiredVideoIds.size,
    alreadyPresent,
    added,
    failed,
  };

  console.log("========================================");
  console.log("[YTWL] SYNC COMPLETE");
  console.log("[YTWL] Result:", result);
  console.log("========================================");

  return result;
}
